### PR TITLE
[WIP] Address fix

### LINKED ISSUE #4: Address is missing suburb so addresses are not being geocoded correctly
The suburb is now appearing in the description.

I've disabled this scraper until it's fixed, **remember to re-enable auto-run when this is fixed**.

### PR DESCRIPTION
**Pull request by JasonThomasData**
Hello, this should fix #4 - sort of. 
Some addresses get mangled so I've done my best with limited time.

### CODE REVIEW

**Comment by JasonThomasData** [comment]
Hiya, I made a new scraper to test it works, here - https://morph.io/JasonThomasData/newcastle_development_applications

**Comment by henare** [comment]
Nice work getting this far @JasonThomasData - this is obviously a tough one! :sweat_smile: 

I've marked this as WIP because we can't merge something with so many broken addresses as these will flow into PlanningAlerts :no_entry_sign: When you have time please come back to this and see if you can finish it :lock_with_ink_pen:

**Comment by JasonThomasData** [comment]
Yeah, I think 1 in every 25 or so is still broken. I started doing it without realising the enormity of it. So, I guess it's a start for now :dancing_men:

**Comment by jamezpolley** [comment]
I'm closing this for two reasons: the council updated their website so this scraper no longer works, and also they're currently working on getting an ATDIS feed set up, which will make things much easier.

Thanks for your work @JasonThomasData - it's a shame we couldn't get this going before the site changed

**Pull request closed without merging**
