### PR TITLE
Update scraper.rb

### PR DESCRIPTION
**Pull request by Old-Bloke**
The html address for Newcastle City DAs has changed. I have inserted the new URL but I'm not completely sure it will work because of the way the page has been structured. What do you think?

Ken

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Oh neat, it's got an RSS feed on it too, if the scraping doesn't work too well.

@Old-Bloke - thanks! The best/easiest way to test is via https://morph.io/scrapers/new - you can create a new scraper pointing at your github repo and run it just like it was in production. I'll do that now just to see if there are structure problems on your behalf.

**Comment by CloCkWeRX** [comment]
Even though it ran successfully, it didn't produce any records at first :( 

I updated it to point at the RSS feed (http://www.newcastle.nsw.gov.au/Special-Pages/MediaFeed.aspx?rss=MediaFiles&directory=Documents&path=Development%20Applications/Weekly%20Notifications)

https://morph.io/CloCkWeRX/newcastle_development_applications - its scraping the feed now (yay) but the PDF structure has changed a bit maybe.

```
Manually ran revision 41c6e95a and completed successfully less than a minute ago.
run time 2 minutes
nothing changed in the database
66 pages scraped
```

Seeing errors like:

```
http://www.newcastle.nsw.gov.au/getmedia/c9416072-cbec-40e2-a75d-59fe4b6ab794/Weekly-Notification-List-for-the-Week-Ending-04-November-2015.aspx?feed=MediaFiles failed
 no implicit conversion of nil into String
```

or

```
Scraping http://www.newcastle.nsw.gov.au/getmedia/fbb05d1e-9693-45b1-a243-4713592c3166/Weekly_Notification_List_for_the_Week_Ending_14_01_2015.aspx?feed=MediaFiles
 http://www.newcastle.nsw.gov.au/getmedia/fbb05d1e-9693-45b1-a243-4713592c3166/Weekly_Notification_List_for_the_Week_Ending_14_01_2015.aspx?feed=MediaFiles failed
 invalid date
```

The fact they are suppressed hints it might be normal; but can't tell. @nik3daz do you have a bit of context?

**Comment by Old-Bloke** [comment]
The pdf from Council doesn't include a 'date submitted' column. The last column of the pdf has beginning and end dates for the public exhibition period in the form 'dd MMMM to dd MMMM YYYY', hence the date_received error. The scraper would need to be able to extract the first of those two dates and include the YYYY to provide the date_received field.

The pdf also has the address in two columns, Street and then Suburb, so the scraper would need to be altered to combine the two columns into one address field.

All that is well beyond my skills. Hopefully, others can get it working.

**Comment by Old-Bloke** [comment]
@CloCkWeRX – Thanks for picking this up. I tried running it in morph.io but got an error message I didn’t understand. I’m really out of my depth here. I had hoped it was simply a problem of a changed URL when council updated its website but there is more to it.

Scraping the RSS feed should work if the scraper code can be changed to match the pdf files. Beyond me I’m afraid.

Ken

**Comment by CloCkWeRX** [comment]
I might close is in favour of #3; which builds on the same kind of change.

**Pull request closed without merging**
